import type { Metadata } from "next";
import { Montserrat, Oswald } from "next/font/google"; // Updated font imports - removed Roboto, added Oswald
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// Configure Oswald for main headers
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald", // CSS variable for Oswald
  weight: ['700'], // Bold weight for headers
});

// Configure Montserrat for sub-headers and body text
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // CSS variable for Montserrat
  weight: ['400', '500', '600', '700', '800'], // Added 800 (ExtraBold) for sub-headers
});

export const metadata: Metadata = {
  title: "Amigo Chat", // Updated title
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={`${oswald.variable} ${montserrat.variable} font-sans antialiased`} // Use Oswald and Montserrat fonts
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark" 
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
